WITH RANKEDDATA AS (
    SELECT
        PROB.PROB_NO,
        PROB.PROB_TITLE,
        PROB.ST_DT,
        PROB.SUBMITTER,
        PROB.STATUS,
        SUBMIT.BAEKJOON_ID,
        PROB.PROB_TIER,
        ROW_NUMBER() OVER (PARTITION BY SUBMIT.PROB_NO ORDER BY MEMORY) AS MEMORYRANK,
        ROW_NUMBER() OVER (PARTITION BY SUBMIT.PROB_NO ORDER BY TIME) AS TIMERANK,
        ROW_NUMBER() OVER (PARTITION BY SUBMIT.PROB_NO ORDER BY CODE_LEN) AS CODELENRANK
    FROM
        PROBLEM_INFORMATION PROB
        LEFT JOIN SUBMISSION_INFORMATION SUBMIT 
        ON SUBMIT.PROB_NO = PROB.PROB_NO
)
, MINIDS AS (
    SELECT
        PROB_NO,
        PROB_TITLE,
        ST_DT,
        SUBMITTER,
        PROB_TIER,
        STATUS,
        MIN(CASE WHEN MEMORYRANK = 1 THEN BAEKJOON_ID END) AS MIN_MEMORY_ID,
        MIN(CASE WHEN TIMERANK = 1 THEN BAEKJOON_ID END) AS MIN_TIME_ID,
        MIN(CASE WHEN CODELENRANK = 1 THEN BAEKJOON_ID END) AS MIN_CODE_LEN_ID
    FROM
        RANKEDDATA
    GROUP BY PROB_NO, PROB_TITLE, ST_DT, SUBMITTER, PROB_TIER, STATUS
)
SELECT
    M.PROB_NO,
    M.PROB_TITLE,
    M.ST_DT,
    M.SUBMITTER,
    M.PROB_TIER,
    M.STATUS,
    SUBMITTER_MEM.IMAGE AS SUBMITTER_IMAGE,
    M.MIN_MEMORY_ID,
    MEM1.IMAGE AS MIN_MEMORY_IMAGE,
    M.MIN_TIME_ID,
    MEM2.IMAGE AS MIN_TIME_IMAGE,
    M.MIN_CODE_LEN_ID,
    MEM3.IMAGE AS MIN_CODE_LEN_IMAGE
FROM
    MINIDS M
LEFT JOIN MEMBER SUBMITTER_MEM ON M.SUBMITTER = SUBMITTER_MEM.GITHUB_ID
LEFT JOIN MEMBER MEM1 ON M.MIN_MEMORY_ID = MEM1.BAEKJOON_ID
LEFT JOIN MEMBER MEM2 ON M.MIN_TIME_ID = MEM2.BAEKJOON_ID
LEFT JOIN MEMBER MEM3 ON M.MIN_CODE_LEN_ID = MEM3.BAEKJOON_ID
ORDER BY
    M.ST_DT DESC